language: rust
sudo: false

script:
  - cargo test
  - cargo doc --no-deps

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh

env:
  global:
      - secure: "T0Xhg/g00jd770P62O/VemKPEv98NLXDqOGVZw1c8hubUDHeZLWuRHPv4n+qLXmCg80gRe5ASF4xmUoxeB9JIYOb+tqZ7Ek7f/OGmFwP5+Kr9YaZMRu69DPueZmc1Q8MT6SkTFDG4WvaMzdz6UfwyLs7MCcwHu3bYAOuD0oPEMo="
